# setting for data source
Source:
  PubMed:
    Active: 'False'
    Label: 'Pubmed Data'
    Url: 'https://pubmed.ncbi.nlm.nih.gov/rss/search/1tQjT4yH2iuqFpDL7Y1nShJmC4kDC5_BJYgw4R1O0BCs-_Nemt/?limit=100&utm_campaign=pubmed-2&fc=20230905093742'
    Origin: 'EN'
    Function: 'get_rss_results'
  CDC:
    Active: 'True'
    Label: 'CDC Data'
    Url: 'https://weekly.chinacdc.cn'
    Origin: 'EN'
    Function: 'get_cdc_results'
  GOV:
    Active: 'True'
    Label: 'GOV Data'
    Url: 'https://www.ndcpa.gov.cn/queryList'
    Data: "{'current': '1', 'pageSize': '10','webSiteCode[]': 'jbkzzx','channelCode[]': 'c100016'}"
    Origin: 'CN'
    Function: 'get_gov_results'
# setting for model
Data:
  translate:
    create: 'gpt-4-1106-preview'
    check: 'gpt-4-1106-preview'
Report:
  cover:
    create: 'dall-e-3'
  abstract: # create_report_summary function
    create: 'gpt-4-1106-preview'
    check: 'gpt-4-1106-preview'
  news: # bing_analysis function
    create: 'gpt-4-all'
    clean: 'gpt-4-1106-preview'
    check: 'gpt-4-1106-preview'
  introduction: # create_report_page function
    create: 'gpt-4'
    check: 'gpt-3.5-turbo'
  highlights: # create_report_page function
    create: 'gpt-4'
    check: 'gpt-3.5-turbo'
  analysis: # create_report_page function
    create: 'gpt-4'
    check: 'gpt-3.5-turbo'
Mail:
  main: # send_mail function
    create: 'gpt-4-1106-preview'
    check: 'gpt-4-1106-preview'
  keywords:
    create: 'gpt-4-1106-preview'
    check: 'gpt-4-1106-preview'
Website:
  main: # create_website function
    create: 'gpt-4-1106-preview'
    check: 'gpt-4-1106-preview'
