name: auto update CDC Monthly Report Data
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 0 6 * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: List files in directory
        run: |
          ls
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'
      - run: pip install requests xmltodict beautifulsoup4 pandas
      - run: python3 ../Script/WeeklyReport/main.py
      - run: python3 ../Script/DatacenterReport/main.py
