name: auto update CDC Monthly Report Data
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 0 6 * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    env:
      OPENAI_api: ${{ secrets.OPENAI_API }}
      OPENAI_url: ${{ secrets.OPENAI_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'
      - run: pip install requests xmltodict beautifulsoup4 pandas reportlab plotnine
      - run: python3 Script/WeeklyReport/main.py
      # - run: python3 Script/WeeklyReport/analysis.py
      - run: python3 Script/DatacenterReport/main.py
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            git config --local user.email "kanggle@outlook.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Auto Update files"
            git push origin main

