name: auto update CDC Monthly Report Data
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 0 6 * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      - run: pip install requests xmltodict beautifulsoup4 pandas
      - run: cd Script
      - run: python GetByPubmed.py
