name: auto update CDC Monthly Report Data

on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron: '0 6 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-22.04
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
      test: ${{ vars.TEST }}
      test_dc: ${{ vars.TEST_DC }}
      test_mail: ${{ vars.TEST_MAIL }}
      send_mail: ${{ vars.SEND_MAIL }}
      smtp_sender: ${{ secrets.SMTP_SENDER }}
      smtp_password: ${{ secrets.SMTP_PASSWORD }}
      smtp_server_url: ${{ secrets.SMTP_SERVER_URL }}
      smtp_server_port: ${{ secrets.SMTP_SERVER_PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'

      - name: Install dependencies
        run: |
          pip install requests==2.31.0 xmltodict==0.13.0 beautifulsoup4==4.12.2 pandas==2.1.4 reportlab==4.0.9 plotnine==0.12.4 onedrivedownloader==1.1.3 openpyxl==3.1.2 tabulate==0.9.0 markdown==3.5.2 plotly==5.18.0 jinja2==3.1.3 openai==1.7.2 pyyaml==6.0.1 PyPDF2==3.0.1 Pillow==10.2.0

      - name: Run Python script
        run: |
          python3 Script/WeeklyReport/main.py
          python3 Script/DatacenterReport/main.py

      - name: Check for changes in a specific file
        id: check_file
        run: |
          if git diff --name-only --exit-code "Report/report latest.pdf"; then
            echo "report_latest.pdf has not changed."
            echo "::set-output name=changed::false"
          else
            echo "report_latest.pdf has changed."
            echo "::set-output name=changed::true"
          fi

      - name: Commit and push changes
        if: steps.check_file.outputs.changed == 'true'
        run: |
          git config --global user.name "xmusphlkg"
          git config --global user.email "kanggle@outlook.com"
          git add .
          git commit -m "Auto update generated files"
          git push origin master
