name: auto update CDC Monthly Report Data

on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron: '0 6 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    env:
      OPENAI_api: ${{ secrets.OPENAI_API }}
      OPENAI_url: ${{ secrets.OPENAI_URL }}
      MS_subscribe: ${{ secrets.MS_SUBSCRIBE }}
      MS_sender_email: ${{ secrets.MS_SENDER_EMAIL }}
      MS_client_id: ${{ secrets.MS_CLIENT_ID }}
      MS_client_secret: ${{ secrets.MS_CLIENT_SECRET }}
      MS_tenant_id: ${{ secrets.MS_TENANT_ID }}
      test: ${{ vars.TEST }}
      test_analysis: ${{ vars.TEST_ANALYSIS }}
      test_dc: ${{ vars.TEST_DC }}
      cite: ${{ vars.CITE }}
      update_info: ${{ vars.UPDATE_INFO }}
      test_mail: ${{ vars.TEST_MAIL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'

      - name: Install dependencies
        run: |
          pip install requests xmltodict beautifulsoup4 pandas reportlab plotnine onedrivedownloader openpyxl tabulate markdown plotly jinja2

      - name: Run Python script
        run: |
          python3 Script/WeeklyReport/main.py
          python3 Script/DatacenterReport/main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "xmusphlkg"
          git config --global user.email "kanggle@outlook.com"
          git add .
          git commit -m "Update generated files"
          git push origin master
